# Generated by Django 2.1.12 on 2019-10-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='shoe_brand',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoes_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoes_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
