# Generated by Django 2.1.12 on 2019-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191004_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='class_category',
            field=models.ManyToManyField(blank=True, to='core.Categories'),
        ),
    ]
